const APIKeys = {
  LIVEPEER_STUDIO_KEY: process.env.NEXT_PUBLIC_LIVEPEER_STUDIO_KEY,
  CONTENTFUL_KEY: process.env.NEXT_PUBLIC_CONTENTFUL_KEY,
  CONTENTFUL_PREVIEW_KEY: process.env.NEXT_Public_CONTENTFUL_PREVIEW_KEY,
  CONTENTFUL_CMA_KEY: process.env.CONTENTFUL_CMA_KEY,
  CONTENTFUL_SPACE_ID: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
  MAGIC_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY,
  MAGIC_SECRET_KEY: process.env.MAGIC_SECRET_KEY,
  BASE_URL: process.env.BASE_URL,
};

export default APIKeys;
